def print_digit(num):
    print(num, end="")

print_digit(8)
print_digit(8)
print_digit(0)
print_digit(0)
print_digit(5)
print_digit(5)
print_digit(5)
print_digit(3)
print_digit(5)
print_digit(3)
print_digit(5)
print()